import { Inter } from 'next/font/google';
import './globals.css';
import PropTypes from 'prop-types';
import { StyledEngineProvider } from '@mui/material';
import CustomThemeProvider from '@/theme/provider';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StyledEngineProvider injectFirst>
          <CustomThemeProvider>{children}</CustomThemeProvider>
        </StyledEngineProvider>
      </body>
    </html>
  );
}

RootLayout.propTypes = {
  children: PropTypes.node.isRequired,
};
